import Link from "next/link"
import type { Metadata } from "next"
import { notFound } from "next/navigation"
import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { DealCard } from "@/components/deal-card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { CapitalOnePromo } from "@/components/capital-one-promo"
import { PageContainer, DealGrid } from "@/components/layout/page-container"
import { createAnonClient } from "@/lib/supabase/anon"
import { getStoreInfo, formatRating, formatReviewCount, type Deal } from "@/lib/deal-types"
import { getTrendingDeals } from "@/lib/deals"
import { 
  TipBox, 
  ExtensionCTA, 
  ShareButtons, 
  NewsletterSignup,
  TableOfContents,
  Divider
} from "@/components/blog/article-components"
import { BlogSidebar } from "@/components/blog/blog-sidebar"
import { categories as blogCategories } from "@/lib/blog-data"
import {
  generateBrandPost,
  generateCategoryPost,
  generateTrendingPost,
  generateArticleSchema,
  generateFAQSchema,
  generateBreadcrumbSchema,
  getAllGeneratedBlogSlugs,
  type GeneratedBlogPost
} from "@/lib/seo/blog-generator"
import { 
  Calendar,
  Clock,
  User,
  ArrowRight,
  ArrowLeft,
  Sparkles,
  ChevronRight,
  CheckCircle2,
  TrendingUp,
  Tag,
  ExternalLink
} from "lucide-react"

export const revalidate = 3600

// Store mapping for legacy pattern
const stores: Record<string, string> = {
  'amazon': 'Amazon',
  'best-buy': 'Best Buy',
  'bestbuy': 'Best Buy',
  'nike': 'Nike',
  'target': 'Target',
  'apple': 'Apple',
  'walmart': 'Walmart',
  'costco': 'Costco',
  'macys': "Macy's",
  'nordstrom': 'Nordstrom',
  'kohls': "Kohl's",
  'home-depot': 'Home Depot',
  'homedepot': 'Home Depot',
  'lowes': "Lowe's",
  'wayfair': 'Wayfair',
  'adidas': 'Adidas',
  'dyson': 'Dyson',
}

// Category mapping for legacy pattern
const categories: Record<string, { name: string; searchTerms: string[] }> = {
  'headphones': { name: 'Headphones', searchTerms: ['headphones', 'earbuds', 'airpods'] },
  'laptops': { name: 'Laptops', searchTerms: ['laptop', 'macbook', 'notebook'] },
  'tvs': { name: 'TVs', searchTerms: ['tv', 'television', 'oled'] },
  'tv': { name: 'TVs', searchTerms: ['tv', 'television', 'oled'] },
  'smartphones': { name: 'Smartphones', searchTerms: ['phone', 'iphone', 'smartphone'] },
  'phones': { name: 'Smartphones', searchTerms: ['phone', 'iphone', 'smartphone'] },
  'running-shoes': { name: 'Running Shoes', searchTerms: ['running', 'shoes'] },
  'sneakers': { name: 'Sneakers', searchTerms: ['sneakers', 'shoes'] },
  'jeans': { name: 'Jeans', searchTerms: ['jeans', 'denim'] },
  'jackets': { name: 'Jackets', searchTerms: ['jacket', 'coat'] },
  'vacuums': { name: 'Vacuums', searchTerms: ['vacuum', 'dyson'] },
  'coffee-makers': { name: 'Coffee Makers', searchTerms: ['coffee', 'espresso'] },
  'air-fryers': { name: 'Air Fryers', searchTerms: ['air fryer'] },
  'furniture': { name: 'Furniture', searchTerms: ['furniture', 'sofa', 'chair'] },
  'mattresses': { name: 'Mattresses', searchTerms: ['mattress', 'bed'] },
}

interface PageProps {
  params: Promise<{ slug: string }>
}

// Parse legacy slug format: best-{store}-{category}-deals
function parseLegacySlug(slug: string): { store: string; category: string } | null {
  const match = slug.match(/^best-(.+?)-(.+?)-deals$/)
  if (match) {
    return { store: match[1], category: match[2] }
  }
  return null
}

// Parse auto-generated blog slug and generate content
function parseAutoGeneratedSlug(slug: string): GeneratedBlogPost | null {
  const year = new Date().getFullYear()
  const month = new Date().toLocaleString('default', { month: 'long' }).toLowerCase()
  
  // Pattern: best-{brand}-deals-today
  const brandTodayMatch = slug.match(/^best-(\w+(?:-\w+)*)-deals-today$/)
  if (brandTodayMatch && !stores[brandTodayMatch[1].toLowerCase()]) {
    // Only match if not a legacy store pattern
    return generateBrandPost(brandTodayMatch[1], 'today')
  }
  
  // Pattern: best-{brand}-deals-week
  const brandWeekMatch = slug.match(/^best-(\w+(?:-\w+)*)-deals-week$/)
  if (brandWeekMatch) {
    return generateBrandPost(brandWeekMatch[1], 'week')
  }
  
  // Pattern: best-{brand}-deals-{month}-{year}
  const brandMonthMatch = slug.match(new RegExp(`^best-(\\w+(?:-\\w+)*)-deals-${month}-${year}$`))
  if (brandMonthMatch) {
    return generateBrandPost(brandMonthMatch[1], 'month')
  }
  
  // Pattern: best-{category}-deals-under-{price}-{year}
  const categoryPriceMatch = slug.match(/^best-(\w+(?:-\w+)*)-deals-under-(\d+)-(\d+)$/)
  if (categoryPriceMatch) {
    const category = categoryPriceMatch[1]
    const price = parseInt(categoryPriceMatch[2])
    const slugYear = parseInt(categoryPriceMatch[3])
    if (slugYear === year) {
      return generateCategoryPost(category, price)
    }
  }
  
  // Pattern: top-trending-deals-week-{week}-{year}
  const trendingMatch = slug.match(/^top-trending-deals-week-(\d+)-(\d+)$/)
  if (trendingMatch) {
    return generateTrendingPost()
  }
  
  return null
}

async function getDeals(storeName: string, categoryInfo: { searchTerms: string[] }): Promise<Deal[]> {
  const supabase = createAnonClient()
  
  const { data: storeDeals } = await supabase
    .from('deals')
    .select('*')
    .eq('is_active', true)
    .ilike('store', `%${storeName}%`)
    .order('discount_percentage', { ascending: false })
    .limit(30)
  
  if (!storeDeals) return []
  
  const filtered = storeDeals.filter(deal => {
    const text = `${deal.title} ${deal.description}`.toLowerCase()
    return categoryInfo.searchTerms.some(term => text.includes(term))
  })
  
  return filtered.length > 0 ? filtered.slice(0, 12) : storeDeals.slice(0, 12)
}

export async function generateStaticParams() {
  // Include both legacy and auto-generated slugs
  const autoGeneratedSlugs = getAllGeneratedBlogSlugs()
  return autoGeneratedSlugs.map(slug => ({ slug }))
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params
  
  // Try auto-generated post first
  const autoPost = parseAutoGeneratedSlug(slug)
  if (autoPost) {
    return {
      title: autoPost.metaTitle,
      description: autoPost.metaDescription,
      keywords: autoPost.keywords,
      openGraph: {
        title: autoPost.metaTitle,
        description: autoPost.metaDescription,
        type: "article",
        publishedTime: autoPost.publishedAt,
        authors: [autoPost.author.name],
        url: `https://savesmart.bio/blog/deals/${slug}`,
      },
      twitter: {
        card: "summary_large_image",
        title: autoPost.metaTitle,
        description: autoPost.metaDescription,
      },
      alternates: {
        canonical: `https://savesmart.bio/blog/deals/${slug}`,
      },
    }
  }
  
  // Try legacy pattern
  const parsed = parseLegacySlug(slug)
  if (!parsed) {
    return { title: 'Deals Guide | SaveSmart' }
  }
  
  const storeName = stores[parsed.store.toLowerCase()]
  const categoryInfo = categories[parsed.category.toLowerCase()]
  
  if (!storeName || !categoryInfo) {
    return { title: 'Deals Guide | SaveSmart' }
  }
  
  const title = `Best ${storeName} ${categoryInfo.name} Deals (${new Date().getFullYear()}) - Verified Discounts`
  const description = `Discover the best ${storeName} ${categoryInfo.name.toLowerCase()} deals for ${new Date().getFullYear()}. Our experts track prices and verify every discount to help you save up to 70%.`
  
  return {
    title,
    description,
    openGraph: {
      title,
      description,
      type: 'article',
      publishedTime: new Date().toISOString(),
      authors: ['SaveSmart Team'],
    },
    alternates: {
      canonical: `https://savesmart.bio/blog/deals/${slug}`,
    },
  }
}

// Extract headings for table of contents
function extractHeadings(content: string): { id: string; text: string; level: number }[] {
  const headings: { id: string; text: string; level: number }[] = []
  const lines = content.split('\n')
  
  lines.forEach((line) => {
    const h2Match = line.match(/^## (.+)$/)
    const h3Match = line.match(/^### (.+)$/)
    
    if (h2Match) {
      const text = h2Match[1].trim()
      const id = text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
      headings.push({ id, text, level: 2 })
    } else if (h3Match) {
      const text = h3Match[1].trim()
      const id = text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
      headings.push({ id, text, level: 3 })
    }
  })
  
  return headings
}

// Format article content with enhanced styling
function formatContent(content: string): string {
  let html = content
    .replace(/^### (.*$)/gm, (_, text) => {
      const id = text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
      return `<h3 id="${id}" class="text-xl font-semibold mt-8 mb-4">${text}</h3>`
    })
    .replace(/^## (.*$)/gm, (_, text) => {
      const id = text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
      return `<h2 id="${id}" class="text-2xl font-bold mt-10 mb-4">${text}</h2>`
    })
    .replace(/^# (.*$)/gm, "")
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" class="text-primary hover:underline">$1</a>')
    .replace(/^- (.*$)/gm, "<li>$1</li>")
    .replace(/^\d+\. (.*$)/gm, "<li>$1</li>")
    .replace(/\|([^|]+)\|/g, (match) => {
      const cells = match.split("|").filter(Boolean)
      return "<tr>" + cells.map((cell) => `<td class="border border-border px-4 py-2">${cell.trim()}</td>`).join("") + "</tr>"
    })
    .split("\n\n")
    .map((para) => {
      if (
        para.startsWith("<h") ||
        para.startsWith("<li") ||
        para.startsWith("<tr") ||
        para.trim() === ""
      ) {
        return para
      }
      if (para.includes("<li>")) {
        return `<ul class="list-disc list-inside space-y-1 my-4 text-muted-foreground">${para}</ul>`
      }
      return `<p class="my-4 leading-relaxed text-muted-foreground">${para}</p>`
    })
    .join("\n")

  return html
}

function getWeekNumber(): number {
  const now = new Date()
  const start = new Date(now.getFullYear(), 0, 1)
  const diff = now.getTime() - start.getTime()
  const oneWeek = 604800000
  return Math.ceil(diff / oneWeek)
}

export default async function BestDealsArticlePage({ params }: PageProps) {
  const { slug } = await params
  
  // Try auto-generated post first
  const autoPost = parseAutoGeneratedSlug(slug)
  if (autoPost) {
    return <AutoGeneratedBlogPage post={autoPost} slug={slug} />
  }
  
  // Fall back to legacy pattern
  const parsed = parseLegacySlug(slug)
  if (!parsed) {
    notFound()
  }
  
  const storeName = stores[parsed.store.toLowerCase()]
  const categoryInfo = categories[parsed.category.toLowerCase()]
  
  if (!storeName || !categoryInfo) {
    notFound()
  }
  
  const deals = await getDeals(storeName, categoryInfo)
  const storeInfo = getStoreInfo(storeName)
  const currentYear = new Date().getFullYear()
  const currentMonth = new Date().toLocaleString('en-US', { month: 'long' })

  const structuredData = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: `Best ${storeName} ${categoryInfo.name} Deals (${currentYear})`,
    description: `Guide to the best ${storeName} ${categoryInfo.name.toLowerCase()} deals with verified discounts.`,
    author: { "@type": "Organization", name: "SaveSmart" },
    publisher: { "@type": "Organization", name: "SaveSmart", logo: { "@type": "ImageObject", url: "https://savesmart.bio/logo.png" } },
    datePublished: new Date().toISOString(),
    dateModified: new Date().toISOString(),
    mainEntityOfPage: `https://savesmart.bio/blog/deals/${slug}`,
  }

  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
      />
      
      <main className="py-12 md:py-16">
        <PageContainer narrow>
          <nav className="mb-6">
            <ol className="flex items-center gap-2 text-sm text-muted-foreground">
              <li><Link href="/blog" className="hover:text-foreground">Blog</Link></li>
              <ChevronRight className="h-4 w-4" />
              <li><Link href={`/deals/${parsed.store}`} className="hover:text-foreground">{storeName} Deals</Link></li>
              <ChevronRight className="h-4 w-4" />
              <li className="text-foreground">{categoryInfo.name}</li>
            </ol>
          </nav>

          <header className="mb-8">
            <Badge className="mb-4 bg-primary/10 text-primary border-0">
              {storeName} Deals Guide
            </Badge>
            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-foreground mb-4 leading-tight">
              Best {storeName} {categoryInfo.name} Deals ({currentYear})
            </h1>
            <p className="text-xl text-muted-foreground mb-6">
              Our team tracks {storeName} prices daily to find the best {categoryInfo.name.toLowerCase()} discounts. 
              Here are the top deals available in {currentMonth} {currentYear}.
            </p>
            <div className="flex flex-wrap items-center gap-4 text-sm text-muted-foreground">
              <span className="flex items-center gap-1.5">
                <User className="h-4 w-4" />
                SaveSmart Team
              </span>
              <span className="flex items-center gap-1.5">
                <Calendar className="h-4 w-4" />
                Updated {currentMonth} {currentYear}
              </span>
              <span className="flex items-center gap-1.5">
                <Clock className="h-4 w-4" />
                {deals.length} Active Deals
              </span>
            </div>
          </header>

          <section className="bg-muted/50 rounded-xl p-6 mb-8">
            <h2 className="text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
              <TrendingUp className="h-5 w-5 text-primary" />
              Quick Summary
            </h2>
            <ul className="space-y-2">
              <li className="flex items-start gap-2">
                <CheckCircle2 className="h-5 w-5 text-green-500 shrink-0 mt-0.5" />
                <span>Best discounts: Up to {Math.max(...deals.map(d => d.discount_percentage), 50)}% off select {categoryInfo.name.toLowerCase()}</span>
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 className="h-5 w-5 text-green-500 shrink-0 mt-0.5" />
                <span>{storeName} rating: {formatRating(storeInfo.rating)} stars ({formatReviewCount(storeInfo.reviewCount)} reviews)</span>
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 className="h-5 w-5 text-green-500 shrink-0 mt-0.5" />
                <span>Active deals: {deals.length} verified {categoryInfo.name.toLowerCase()} offers</span>
              </li>
            </ul>
          </section>

          <article className="article-content mb-12">
            <h2>How We Find the Best {storeName} {categoryInfo.name} Deals</h2>
            <p>
              Finding genuine discounts on {categoryInfo.name.toLowerCase()} at {storeName} isn&apos;t always straightforward. 
              Retailers often inflate &quot;original&quot; prices to make sales look more impressive than they are. 
              That&apos;s why we track price history and verify every deal before including it in this guide.
            </p>
            <p>
              Our process is simple: we monitor {storeName}&apos;s {categoryInfo.name.toLowerCase()} prices daily, 
              compare them against historical data, and only feature deals that represent real savings. 
              If a &quot;50% off&quot; deal was actually the normal price last month, you won&apos;t find it here.
            </p>

            <h2>Current {storeName} {categoryInfo.name} Deals</h2>
            <p>
              Here are the best {categoryInfo.name.toLowerCase()} deals we&apos;ve found at {storeName} this month. 
              All prices are verified and discounts are calculated against actual historical prices.
            </p>
          </article>

          {deals.length > 0 ? (
            <section className="mb-12">
              <DealGrid columns={3}>
                {deals.slice(0, 6).map((deal) => (
                  <DealCard key={deal.id} deal={deal} />
                ))}
              </DealGrid>
              {deals.length > 6 && (
                <div className="mt-6 text-center">
                  <Button variant="outline" size="lg" asChild>
                    <Link href={`/deals/${parsed.store}`}>
                      View All {storeName} Deals
                      <ArrowRight className="h-4 w-4 ml-2" />
                    </Link>
                  </Button>
                </div>
              )}
            </section>
          ) : (
            <section className="mb-12 text-center py-12 bg-muted/30 rounded-xl">
              <Sparkles className="h-12 w-12 text-muted-foreground/50 mx-auto mb-4" />
              <p className="text-muted-foreground mb-4">
                No {categoryInfo.name.toLowerCase()} deals from {storeName} at the moment.
              </p>
              <Button asChild>
                <Link href={`/deals/${parsed.store}`}>Browse All {storeName} Deals</Link>
              </Button>
            </section>
          )}

          <article className="article-content mb-12">
            <h2>Tips for Getting the Best {storeName} {categoryInfo.name} Deals</h2>
            
            <h3>1. Use Price Tracking Tools</h3>
            <p>
              Prices on {categoryInfo.name.toLowerCase()} fluctuate frequently. A browser extension like SaveSmart 
              can show you the price history so you know if a &quot;sale&quot; is actually a good deal.
            </p>

            <h3>2. Stack Discounts</h3>
            <p>
              Don&apos;t just accept the sticker price. Look for coupon codes, cashback offers, and credit card rewards 
              that can stack on top of {storeName}&apos;s sale prices.
            </p>

            <h3>3. Know the Best Times to Buy</h3>
            <p>
              {storeName} typically has major sales during Black Friday, Prime Day (if applicable), and seasonal events. 
              If your purchase can wait, tracking these dates can lead to bigger savings.
            </p>
          </article>

          <CapitalOnePromo variant="inline" />

          <section className="mt-12 border-t border-border pt-8">
            <h2 className="text-xl font-bold text-foreground mb-4">Related Deal Guides</h2>
            <div className="grid gap-4 sm:grid-cols-2">
              <Link 
                href={`/deals/${parsed.store}`}
                className="p-4 rounded-lg border border-border hover:border-primary transition-colors"
              >
                <span className="font-medium">All {storeName} Deals</span>
                <p className="text-sm text-muted-foreground">Browse every active {storeName} discount</p>
              </Link>
              <Link 
                href={`/deals/${parsed.category}`}
                className="p-4 rounded-lg border border-border hover:border-primary transition-colors"
              >
                <span className="font-medium">{categoryInfo.name} at All Stores</span>
                <p className="text-sm text-muted-foreground">Compare {categoryInfo.name.toLowerCase()} prices everywhere</p>
              </Link>
            </div>
          </section>

          <section className="mt-12 text-center bg-muted/30 rounded-xl p-8">
            <h2 className="text-2xl font-bold text-foreground mb-2">
              Never Miss a {storeName} Deal
            </h2>
            <p className="text-muted-foreground mb-6">
              Install SaveSmart to get automatic price tracking and coupon codes at checkout.
            </p>
            <Button size="lg" className="gap-2" asChild>
              <Link href="/deal-finder">
                <Sparkles className="h-5 w-5" />
                Get SaveSmart Free
              </Link>
            </Button>
          </section>
        </PageContainer>
      </main>

      <Footer />
    </div>
  )
}

// Component for auto-generated blog posts
async function AutoGeneratedBlogPage({ post, slug }: { post: GeneratedBlogPost; slug: string }) {
  const category = blogCategories.find((c) => c.slug === post.category)
  const headings = extractHeadings(post.content)
  
  let trendingDeals: Awaited<ReturnType<typeof getTrendingDeals>> = []
  try {
    trendingDeals = await getTrendingDeals(4)
  } catch {
    // Continue without deals
  }

  const articleUrl = `https://savesmart.bio/blog/deals/${slug}`
  
  const articleSchema = generateArticleSchema(post)
  const faqSchema = generateFAQSchema(post.faqs)
  const breadcrumbSchema = generateBreadcrumbSchema(post)

  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />

      <main>
        <section className="border-b border-border bg-gradient-to-b from-muted/50 to-background py-12 md:py-16">
          <PageContainer narrow>
            <Link
              href="/blog"
              className="group inline-flex items-center gap-2 text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
            >
              <ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-1" />
              Back to Blog
            </Link>

            <nav className="mt-4 flex items-center gap-2 text-sm text-muted-foreground">
              <Link href="/" className="hover:text-foreground">Home</Link>
              <span>/</span>
              <Link href="/blog" className="hover:text-foreground">Blog</Link>
              <span>/</span>
              <Link href="/blog" className="hover:text-foreground">Deals</Link>
              <span>/</span>
              <span className="text-foreground truncate max-w-[200px]">{post.title}</span>
            </nav>

            <div className="mt-8 flex flex-wrap items-center gap-4 text-sm text-muted-foreground">
              <Link
                href={`/blog/category/${post.category}`}
                className={`inline-flex items-center rounded-md px-2.5 py-0.5 text-xs font-medium text-white transition-opacity hover:opacity-90 ${
                  category?.color || "bg-primary"
                }`}
              >
                {category?.name || post.category}
              </Link>
              <span className="flex items-center gap-1.5">
                <Calendar className="h-4 w-4" />
                {new Date(post.publishedAt).toLocaleDateString("en-US", {
                  year: "numeric",
                  month: "long",
                  day: "numeric",
                })}
              </span>
              <span className="flex items-center gap-1.5">
                <Clock className="h-4 w-4" />
                {post.readTime}
              </span>
            </div>

            <h1 className="mt-6 text-4xl font-bold tracking-tight text-foreground sm:text-5xl lg:text-6xl text-balance leading-tight">
              {post.title}
            </h1>

            <p className="mt-6 text-xl text-muted-foreground leading-relaxed text-pretty max-w-3xl">
              {post.excerpt}
            </p>

            <div className="mt-10 flex items-center justify-between flex-wrap gap-4">
              <div className="flex items-center gap-4">
                <div className="flex h-14 w-14 items-center justify-center rounded-full bg-primary/10">
                  <User className="h-7 w-7 text-primary" />
                </div>
                <div>
                  <p className="font-semibold text-foreground">{post.author.name}</p>
                  <p className="text-sm text-muted-foreground">{post.author.role}</p>
                </div>
              </div>
              <ShareButtons url={articleUrl} title={post.title} />
            </div>
          </PageContainer>
        </section>

        <section className="py-12 md:py-16">
          <PageContainer>
            <div className="flex gap-12">
              <div className="min-w-0 flex-1 max-w-3xl">
                <div className="lg:hidden">
                  <TableOfContents items={headings} />
                </div>

                <article className="article-content">
                  <div dangerouslySetInnerHTML={{ __html: formatContent(post.content) }} />
                </article>

                {post.internalLinks.length > 0 && (
                  <div className="mt-12 rounded-xl border border-border bg-muted/30 p-6">
                    <h3 className="font-semibold text-foreground mb-4 flex items-center gap-2">
                      <ExternalLink className="h-5 w-5" />
                      Related Deal Pages
                    </h3>
                    <div className="flex flex-wrap gap-2">
                      {post.internalLinks.map((link, index) => (
                        <Link
                          key={index}
                          href={link.href}
                          className="inline-flex items-center gap-1 rounded-full bg-background px-4 py-2 text-sm font-medium text-foreground border border-border hover:border-primary hover:text-primary transition-colors"
                        >
                          {link.text}
                          <ArrowRight className="h-3 w-3" />
                        </Link>
                      ))}
                    </div>
                  </div>
                )}

                {post.faqs.length > 0 && (
                  <div className="mt-12">
                    <h2 className="text-2xl font-bold text-foreground mb-6">
                      Frequently Asked Questions
                    </h2>
                    <div className="space-y-4">
                      {post.faqs.map((faq, index) => (
                        <div
                          key={index}
                          className="rounded-xl border border-border bg-card p-6"
                        >
                          <h3 className="font-semibold text-foreground mb-2">
                            {faq.question}
                          </h3>
                          <p className="text-muted-foreground leading-relaxed">
                            {faq.answer}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                <div className="mt-8">
                  <TipBox variant="tip" title="Save Even More">
                    Install the SaveSmart browser extension to automatically find and apply coupon codes at checkout. Works on 50,000+ stores.
                  </TipBox>
                </div>

                <Divider />

                <ExtensionCTA />

                <div className="mt-12 space-y-8">
                  <div className="flex flex-wrap items-center gap-2 pt-8 border-t border-border">
                    <Tag className="h-4 w-4 text-muted-foreground" />
                    {post.keywords.map((keyword, index) => (
                      <Badge key={index} variant="secondary" className="text-xs">
                        {keyword}
                      </Badge>
                    ))}
                  </div>
                  
                  <div className="flex items-center justify-between gap-4">
                    <ShareButtons url={articleUrl} title={post.title} />
                    <Button variant="outline" asChild>
                      <Link href="/deals/trending">
                        View Trending Deals
                        <ArrowRight className="ml-2 h-4 w-4" />
                      </Link>
                    </Button>
                  </div>

                  <NewsletterSignup />
                </div>
              </div>

              <BlogSidebar 
                popularDeals={trendingDeals} 
                relatedPosts={[]} 
              />
            </div>
          </PageContainer>
        </section>

        <section className="border-t border-border bg-muted/30 py-12 md:py-16">
          <PageContainer>
            <h2 className="text-2xl font-bold text-foreground">More Deal Guides</h2>
            <p className="mt-2 text-muted-foreground">
              Discover more ways to save with our expert deal guides.
            </p>

            <div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {[
                { title: "Best Laptop Deals Under $500", href: `/blog/deals/best-laptops-deals-under-500-${new Date().getFullYear()}`, category: "Laptops" },
                { title: "Top Nike Deals This Week", href: "/blog/deals/best-nike-deals-week", category: "Fashion" },
                { title: "Best Headphone Deals Under $100", href: `/blog/deals/best-headphones-deals-under-100-${new Date().getFullYear()}`, category: "Audio" },
                { title: "Best Apple Deals This Week", href: "/blog/deals/best-apple-deals-week", category: "Electronics" },
                { title: "Best TV Deals Under $500", href: `/blog/deals/best-tvs-deals-under-500-${new Date().getFullYear()}`, category: "TVs" },
                { title: "Weekly Trending Deals", href: `/blog/deals/top-trending-deals-week-${getWeekNumber()}-${new Date().getFullYear()}`, category: "Trending" },
              ].map((article, index) => (
                <Link
                  key={index}
                  href={article.href}
                  className="group overflow-hidden rounded-2xl border border-border bg-card transition-all duration-300 hover:shadow-lg hover:-translate-y-1"
                >
                  <div className="bg-primary/10 flex h-32 items-center justify-center">
                    <Tag className="h-10 w-10 text-primary/60" />
                  </div>
                  <div className="p-5">
                    <Badge variant="secondary" className="bg-primary/10 text-primary border-0">
                      {article.category}
                    </Badge>
                    <h3 className="mt-3 font-semibold text-foreground transition-colors group-hover:text-primary line-clamp-2">
                      {article.title}
                    </h3>
                    <div className="mt-4 flex items-center gap-1 text-sm font-medium text-primary">
                      Read Guide
                      <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
                    </div>
                  </div>
                </Link>
              ))}
            </div>
          </PageContainer>
        </section>
      </main>

      <Footer />
    </div>
  )
}
